name: bobby_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  url_launcher: ^6.3.0
  firebase_core: ^3.5.0
  firebase_remote_config: ^5.0.0
  bobby_portfolio_package:
    path: ./package/ui/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
